# Generated by Django 4.0.4 on 2022-05-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('ida_ao_ar', models.DateField()),
                ('episodio', models.CharField(max_length=16)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'Episodio',
                'verbose_name_plural': 'Episodios',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('dimensao', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('id_personagem', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('V', 'Vivo'), ('M', 'Morto'), ('D', 'Desconhecido')], default='D', max_length=1)),
                ('especie', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('D', 'Desconhecido')], default='D', max_length=1)),
                ('imagem', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('url', models.URLField(unique=True)),
                ('episodio', models.ManyToManyField(blank=True, null=True, related_name='episodio_personagem', to='rickandmorty.episodio')),
                ('localizacao', models.ManyToManyField(related_name='localizacao_personagem', to='rickandmorty.localizacao')),
                ('origem', models.ManyToManyField(related_name='origem_personagem', to='rickandmorty.localizacao')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
            },
        ),
        migrations.AddField(
            model_name='localizacao',
            name='residentes',
            field=models.ManyToManyField(blank=True, null=True, related_name='localizacao_residente', to='rickandmorty.personagem'),
        ),
        migrations.AddField(
            model_name='episodio',
            name='personagens',
            field=models.ManyToManyField(blank=True, null=True, related_name='episodio_personagens', to='rickandmorty.personagem'),
        ),
    ]
