# Generated by Django 4.0.4 on 2022-05-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickandmorty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('D', 'Desconhecido')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='status',
            field=models.CharField(choices=[('V', 'Vivo'), ('D', 'Desconhecido'), ('M', 'Morto')], default='D', max_length=1),
        ),
    ]
