# Generated by Django 4.0.4 on 2022-05-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickandmorty', '0002_alter_personagem_genero_alter_personagem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='status',
            field=models.CharField(choices=[('D', 'Desconhecido'), ('M', 'Morto'), ('V', 'Vivo')], default='D', max_length=1),
        ),
    ]
