# Generated by Django 4.0.4 on 2022-05-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickandmorty', '0003_alter_personagem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='personagens',
            field=models.ManyToManyField(blank=True, related_name='episodio_personagens', to='rickandmorty.personagem'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='residentes',
            field=models.ManyToManyField(blank=True, related_name='localizacao_residente', to='rickandmorty.personagem'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='episodio',
            field=models.ManyToManyField(blank=True, related_name='episodio_personagem', to='rickandmorty.episodio'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='status',
            field=models.CharField(choices=[('M', 'Morto'), ('V', 'Vivo'), ('D', 'Desconhecido')], default='D', max_length=1),
        ),
    ]
