# Generated by Django 4.0.4 on 2022-05-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickandmorty', '0005_rename_id_personagem_personagem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='status',
            field=models.CharField(choices=[('M', 'Morto'), ('D', 'Desconhecido'), ('V', 'Vivo')], default='D', max_length=1),
        ),
    ]
