# Generated by Django 4.0.4 on 2022-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickandmorty', '0007_alter_episodio_id_alter_localizacao_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('personagens', models.URLField()),
                ('localizacoes', models.URLField()),
                ('episodios', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='personagem',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('D', 'Desconhecido')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='status',
            field=models.CharField(choices=[('V', 'Vivo'), ('M', 'Morto'), ('D', 'Desconhecido')], default='D', max_length=1),
        ),
    ]
