# Generated by Django 4.0.4 on 2022-05-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickandmorty', '0008_home_alter_personagem_genero_alter_personagem_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Index',
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Index', 'verbose_name_plural': 'Index'},
        ),
        migrations.AlterField(
            model_name='personagem',
            name='genero',
            field=models.CharField(choices=[('D', 'Desconhecido'), ('F', 'Feminino'), ('M', 'Masculino')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='status',
            field=models.CharField(choices=[('D', 'Desconhecido'), ('V', 'Vivo'), ('M', 'Morto')], default='D', max_length=1),
        ),
    ]
